### ISSUE TITLE
Server appears to still have lock poisoning issues

### ISSUE THREAD

**Issue by sfackler** [jwilm/racerd#18]
#9's closed, but it looks like the issue wasn't fully resolved. Here's the top chunk of stderr output. The `PoisonError` stack trace repeats from there. I'm running ea325c3
```
bogofile:3:1: 3:2 error: expected one of `;` or `as`, found `#`
bogofile:3 #[derive(Deserialize)]
           ^
bogofile:3:1: 3:2 error: expected one of `;` or `as`, found `#`
bogofile:3 #[derive(Deserialize)]
           ^
bogofile:1:13: 1:14 error: expected one of `::`, `;`, or `as`, found `{`
bogofile:1 use serde::d{Deserialize, Deserializer};
                       ^
bogofile:3:1: 3:2 error: expected one of `;` or `as`, found `#`
bogofile:3 #[derive(Deserialize)]
           ^
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
bogofile:0:1: 0:1 error: unexpected token: `<eof>`
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:366
stack backtrace:
   1:     0x56006ae87b30 - sys::backtrace::tracing::imp::write::h1fe79f3711caca0eUnt
   2:     0x56006ae8a075 - panicking::log_panic::_<closure>::closure.39701
   3:     0x56006ae89ac1 - panicking::log_panic::hffc6d029fed602571nx
   4:     0x56006ae76203 - sys_common::unwind::begin_unwind_inner::h7045c1c64d9ab8edYgs
   5:     0x56006ae76878 - sys_common::unwind::begin_unwind_fmt::h40ee994bfe85f7a54fs
   6:     0x56006ae87201 - rust_begin_unwind
   7:     0x56006aeb802f - panicking::panic_fmt::h4c8d12e3c05f3b8cZEK
   8:     0x56006aeb3d68 - panicking::panic::hb8a57f0c8013c90awDK
   9:     0x56006ac5ffb9 - typeinf::get_type_of_match::h690bc0039f97ab31Jnd
  10:     0x56006ac55815 - ast::_<impl>::visit_expr::h2339d598ffc95851dbc
  11:     0x56006ac3e964 - ast::get_type_of::h63c35bfeb3ef3429xTc
  12:     0x56006ac3b211 - core::complete_from_file::hd3cf610ec43f9051pZa
  13:     0x56006ac32181 - engine::racer::_<impl>::list_completions::h480dbab7125a2668S3a
  14:     0x56006ac2c750 - http::completion::list::h29a4c4cc7aeb4fb1Ita
  15:     0x56006abfdd4b - middleware::_<impl>::handle::handle::h10661862516855150861
  16:     0x56006ae20ba0 - middleware::_<impl>::handle::h9f57b88dbf2e8eb4Coa
  17:     0x56006add23c5 - router::_<impl>::handle_method::h8633d57a725f79b1iia
  18:     0x56006add3993 - router::_<impl>::handle::ha4490428d338984flja
  19:     0x56006ae207e8 - middleware::_<impl>::continue_from_handler::hb66b53442808508drma
  20:     0x56006ae1e87a - middleware::_<impl>::handle::h82115d9a4fc77891yia
  21:     0x56006ac11dd9 - hyper::server::listener::spawn_with::_<closure>::closure.14072
  22:     0x56006ac1073a - sys_common::unwind::try::try_fn::try_fn::h6106811361401582808
  23:     0x56006ae87068 - __rust_try
  24:     0x56006ae83c6b - sys_common::unwind::try::inner_try::h0c3b0e63f018cc29wds
  25:     0x56006ac146d8 - boxed::_<impl>::call_box::call_box::h8677866214614970001
  26:     0x56006ae88b63 - sys::thread::_<impl>::new::thread_start::h85eb4d682b5d5d4ffGw
  27:     0x7f206d78a4a3 - start_thread
  28:     0x7f206df8b13c - clone
  29:                0x0 - <unknown>
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:738
stack backtrace:
   1:     0x56006ae87b30 - sys::backtrace::tracing::imp::write::h1fe79f3711caca0eUnt
   2:     0x56006ae8a075 - panicking::log_panic::_<closure>::closure.39701
   3:     0x56006ae89ac1 - panicking::log_panic::hffc6d029fed602571nx
   4:     0x56006ae76203 - sys_common::unwind::begin_unwind_inner::h7045c1c64d9ab8edYgs
   5:     0x56006ae76878 - sys_common::unwind::begin_unwind_fmt::h40ee994bfe85f7a54fs
   6:     0x56006ae87201 - rust_begin_unwind
   7:     0x56006aeb802f - panicking::panic_fmt::h4c8d12e3c05f3b8cZEK
   8:     0x56006ac2edf6 - http::completion::list::h29a4c4cc7aeb4fb1Ita
   9:     0x56006abfdd4b - middleware::_<impl>::handle::handle::h10661862516855150861
  10:     0x56006ae20ba0 - middleware::_<impl>::handle::h9f57b88dbf2e8eb4Coa
  11:     0x56006add23c5 - router::_<impl>::handle_method::h8633d57a725f79b1iia
  12:     0x56006add3993 - router::_<impl>::handle::ha4490428d338984flja
  13:     0x56006ae207e8 - middleware::_<impl>::continue_from_handler::hb66b53442808508drma
  14:     0x56006ae1e87a - middleware::_<impl>::handle::h82115d9a4fc77891yia
  15:     0x56006ac11dd9 - hyper::server::listener::spawn_with::_<closure>::closure.14072
  16:     0x56006ac1073a - sys_common::unwind::try::try_fn::try_fn::h6106811361401582808
  17:     0x56006ae87068 - __rust_try
  18:     0x56006ae83c6b - sys_common::unwind::try::inner_try::h0c3b0e63f018cc29wds
  19:     0x56006ac146d8 - boxed::_<impl>::call_box::call_box::h8677866214614970001
  20:     0x56006ae88b63 - sys::thread::_<impl>::new::thread_start::h85eb4d682b5d5d4ffGw
  21:     0x7f206d78a4a3 - start_thread
  22:     0x7f206df8b13c - clone
  23:                0x0 - <unknown>
```

**Comment by sfackler** [comment]
Another panic source:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', ../src/libcore/result.rs:738
stack backtrace:
   1:        0x10eab50e8 - sys::backtrace::tracing::imp::write::h06df28c2a8d245f9t9s
   2:        0x10eab69ef - panicking::log_panic::_<closure>::closure.39451
   3:        0x10eab6492 - panicking::log_panic::h9348b1b0af36ae6aCYw
   4:        0x10eaa47c6 - sys_common::unwind::begin_unwind_inner::h005d402245ebd8560cs
   5:        0x10eaa4b6e - sys_common::unwind::begin_unwind_fmt::h440d2eb18c439fa86bs
   6:        0x10eab4777 - rust_begin_unwind
   7:        0x10ead83d0 - panicking::panic_fmt::h4c8d12e3c05f3b8cZEK
   8:        0x10e8b6704 - nameres::get_crate_file::h3d001bbdcc096430Roe
   9:        0x10e8b20ab - nameres::resolve_name::hdf75f840e8b97454EZe
  10:        0x10e86db99 - nameres::resolve_path::h613a3e355649c31fv9e
  11:        0x10e86e027 - nameres::resolve_path::h613a3e355649c31fv9e
  12:        0x10e86b879 - core::complete_from_file::hdeba4eae758ef560pZa
  13:        0x10e861eac - engine::racer::_<impl>::list_completions::h480dbab7125a2668S3a
  14:        0x10e85c3eb - http::completion::list::h29a4c4cc7aeb4fb1Ita
  15:        0x10e82d920 - middleware::_<impl>::handle::handle::h3548267136203250119
  16:        0x10ea4cf55 - middleware::_<impl>::handle::h113d1c7091e38fcbCoa
  17:        0x10e9ff743 - router::_<impl>::handle_method::h8633d57a725f79b1iia
  18:        0x10ea00bb7 - router::_<impl>::handle::ha4490428d338984flja
  19:        0x10ea4cc5a - middleware::_<impl>::continue_from_handler::hd826d3b89872439drma
  20:        0x10ea4b41f - middleware::_<impl>::handle::h13fa1f5743df6cfbyia
  21:        0x10e84217c - hyper::server::listener::spawn_with::_<closure>::closure.14048
  22:        0x10e84091e - sys_common::unwind::try::try_fn::try_fn::h3073949110300619339
  23:        0x10eab45b8 - __rust_try
  24:        0x10eab1f9e - sys_common::unwind::try::inner_try::hcc3a84c80e36120fy9r
  25:        0x10e844aed - boxed::_<impl>::call_box::call_box::h15687704257173693292
  26:        0x10eab5dad - sys::thread::_<impl>::new::thread_start::h5776bf5f72f331a7Rvw
  27:     0x7fff91972059 - _pthread_body
  28:     0x7fff91971fd6 - _pthread_start
```
